export default async function handler(req, res) {
  if (req.method === 'OPTIONS') {
    res.setHeader('Access-Control-Allow-Origin', '*');
    res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
    res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
    return res.status(200).end();
  }
  if (req.method !== 'POST') return res.status(405).send('Method not allowed');

  const { symptoms, patient_id } = req.body;
  const SARVAM_API_KEY = process.env.SARVAM_API_KEY;

  try {
    const response = await fetch("https://api.sarvam.ai/v1/chat/completions", {
      method: "POST",
      headers: {
        "Authorization": `Bearer ${SARVAM_API_KEY}`,
        "Content-Type": "application/json"
      },
      body: JSON.stringify({
        model: "sarvam-105b",
        messages: [
          { role: "system", content: "You are an expert clinical scribe. Generate a brief clinical 'Plan' section based on the symptoms. Respond with ONLY the plan text." },
          { role: "user", content: `Symptoms: ${symptoms || 'General discomfort'}` }
        ],
        temperature: 0.2,
        max_tokens: 500
      })
    });

    const data = await response.json();
    let plan = "Plan generated by Sarvam AI...";
    if (data && data.choices && data.choices.length > 0) {
       plan = data.choices[0].message.content;
    }
    
    res.setHeader('Access-Control-Allow-Origin', '*');
    return res.status(200).json({ plan: plan });
  } catch (error) {
    return res.status(500).json({ error: error.message });
  }
}
